import Navbar from "@/components/Navbar";
import { Provider } from "@/providers";
import "@/styles/globals.css";
import { type Metadata } from "next";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  subsets: ['latin'],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${raleway.variable}`}>
      <body>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
